args = {}
args['use_cuda'] = True
args['encoder_size'] = 64
args['decoder_size'] = 128
args['in_length'] = 13
args['out_length'] = 25
args['grid_size'] = (11, 1)
args['soc_conv_depth'] = 64
args['conv_3x1_depth'] = 16
args['dyn_embedding_size'] = 32
args['input_embedding_size'] = 32
args['batch_size'] = 256
args['num_lat_classes'] = 8
args['num_lon_classes'] = 3
args['use_maneuvers'] = True
args['train_flag'] = False
args['use_planning'] = True
args['val_use_mse']=True
